branch-defaults:
  default:
    environment: protein-explorer-backend
    group_suffix: null
global:
  application_name: protein-explorer-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
